= Caratteristiche
:allow-uri-read: 




== Caratteristiche

Astra Control offre funzionalità critiche per la gestione del ciclo di vita dei dati delle applicazioni Kubernetes:

* Gestire automaticamente lo storage persistente
* Creazione di snapshot e backup on-demand basati sulle applicazioni
* Automatizzare le operazioni di backup e snapshot basate su policy
* Migrare applicazioni e dati da un cluster Kubernetes a un altro
* Replica delle applicazioni su un sistema remoto utilizzando la tecnologia NetApp SnapMirror (Astra Control Center)
* Clonare le applicazioni dallo staging alla produzione
* Visualizzare lo stato di salute e protezione dell'applicazione
* Utilizzare un'interfaccia utente Web o un'API per implementare i flussi di lavoro di backup e migrazione




== Modelli di implementazione

Astra Control è disponibile in due modelli di implementazione:

* *Astra Control Service*: Un servizio gestito da NetApp che offre la gestione dei dati application-aware dei cluster Kubernetes in ambienti di cloud provider multipli, oltre ai cluster Kubernetes autogestiti.
* *Astra Control Center*: Software autogestito che fornisce la gestione dei dati applicativa dei cluster Kubernetes in esecuzione nel tuo ambiente on-premise. Il centro di controllo Astra può essere installato anche in ambienti di cloud provider multipli con un backend di storage NetApp Cloud Volumes ONTAP.


[cols="1h,2d,2a"]
|===
|  | Servizio di controllo Astra | Centro di controllo Astra 


| Come viene offerto? | Come servizio cloud completamente gestito da NetApp  a| 
Come software che puoi scaricare, installare e gestire



| Dove è ospitato? | Su un cloud pubblico scelto da NetApp  a| 
Sul tuo cluster Kubernetes



| Come viene aggiornato? | Gestito da NetApp  a| 
Gli aggiornamenti vengono gestiti



| Quali sono i backend di storage supportati?  a| 
* Servizi Web Amazon:
+
** Amazon EBS
** Amazon FSX per NetApp ONTAP
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


* Google Cloud:
+
** Disco persistente di Google
** NetApp Cloud Volumes Service
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


* Microsoft Azure:
+
** Dischi gestiti Azure
** Azure NetApp Files
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Cloud Volumes ONTAP"^]


* Cluster a gestione automatica:
+
** Amazon EBS
** Dischi gestiti Azure
** Disco persistente di Google
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
** NetApp MetroCluster
** https://longhorn.io/["Longhorn"^]


* Cluster on-premise:
+
** NetApp MetroCluster
** Sistemi NetApp ONTAP AFF e FAS
** NetApp ONTAP Select
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
** https://longhorn.io/["Longhorn"^]



 a| 
* Sistemi NetApp ONTAP AFF e FAS
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]


|===


== Come funziona Astra Control Service

Astra Control Service è un servizio cloud gestito da NetApp sempre attivo e aggiornato con le funzionalità più recenti. Utilizza diversi componenti per consentire la gestione del ciclo di vita dei dati delle applicazioni.

Ad alto livello, Astra Control Service funziona come segue:

* Per iniziare a utilizzare Astra Control Service, devi configurare il tuo cloud provider e registrarti per un account Astra.
+
** Per i cluster GKE, Astra Control Service utilizza https://cloud.netapp.com/cloud-volumes-service-for-gcp["NetApp Cloud Volumes Service per Google Cloud"^] O Google Persistent Disks come back-end di storage per i volumi persistenti.
** Per i cluster AKS, Astra Control Service utilizza https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^] O Azure Managed Disks come back-end di storage per i volumi persistenti.
** Per i cluster Amazon EKS, Astra Control Service utilizza https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^] oppure https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX per NetApp ONTAP"^] come back-end di storage per i volumi persistenti.


* Aggiungi il tuo primo calcolo Kubernetes ad Astra Control Service. Astra Control Service esegue le seguenti operazioni:
+
** Crea un archivio di oggetti nel tuo account cloud provider, dove vengono memorizzate le copie di backup.
+
In Azure, Astra Control Service crea anche un gruppo di risorse, un account di storage e chiavi per il container Blob.

** Crea un nuovo ruolo di amministratore e un nuovo account del servizio Kubernetes sul cluster.
** Utilizza il nuovo ruolo di amministratore per l'installazione https://docs.netapp.com/us-en/trident/index.html["Astra Trident"^] sul cluster e per creare una o più classi di storage.
** Se utilizzi un'offerta di cloud service storage NetApp come back-end dello storage, Astra Control Service utilizza Astra Trident per eseguire il provisioning di volumi persistenti per le tue applicazioni. Se si utilizzano dischi gestiti Amazon EBS o Azure come back-end dello storage, è necessario installare un driver CSI specifico del provider. Le istruzioni di installazione sono fornite in https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-amazon-web-services.html["Configurare Amazon Web Services"^] e. https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html["Configurare Microsoft Azure con dischi gestiti Azure"^].


* A questo punto, è possibile aggiungere applicazioni al cluster. Il provisioning dei volumi persistenti verrà eseguito sulla nuova classe di storage predefinita.
* Quindi, utilizza Astra Control Service per gestire queste applicazioni e iniziare a creare snapshot, backup e cloni.


Il piano gratuito di Astra Control ti consente di gestire fino a 10 spazi dei nomi nel tuo account. Se desideri gestire più di 10, dovrai impostare la fatturazione eseguendo l'aggiornamento dal piano gratuito al piano Premium.



== Come funziona Astra Control Center

Astra Control Center viene eseguito localmente nel tuo cloud privato.

Il centro di controllo Astra supporta i cluster Kubernetes con classe di storage basata su Astra Trident con un backend di storage ONTAP 9.5 e superiore.

In un ambiente connesso al cloud, Astra Control Center utilizza Cloud Insights per fornire monitoraggio e telemetria avanzati. In assenza di una connessione Cloud Insights, il monitoraggio e la telemetria sono disponibili in un centro di controllo Astra per un periodo di 7 giorni ed esportati anche in strumenti di monitoraggio nativi Kubernetes (come Prometheus e Grafana) attraverso endpoint di metriche aperte.

Il centro di controllo Astra è completamente integrato nell'ecosistema AutoSupport e Active IQ per fornire agli utenti e al supporto NetApp informazioni sulla risoluzione dei problemi e sull'utilizzo.

Puoi provare Astra Control Center utilizzando una licenza di valutazione integrata della durata di 90 giorni. Mentre stai valutando Astra Control Center, puoi ottenere supporto tramite e-mail e opzioni della community. Inoltre, puoi accedere agli articoli e alla documentazione della Knowledge base dalla dashboard di supporto all'interno del prodotto.

Per installare e utilizzare Astra Control Center, è necessario soddisfare determinati requisiti https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html["requisiti"^].

Ad alto livello, Astra Control Center funziona come segue:

* Astra Control Center viene installato nel proprio ambiente locale. Scopri di più su come https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html["Installare Astra Control Center"^].
* È possibile completare alcune attività di configurazione, come ad esempio:
+
** Impostare la licenza.
** Aggiungere il primo cluster.
** Aggiungere il backend di storage rilevato quando si aggiunge il cluster.
** Aggiungi un bucket di store di oggetti che memorizzerà i backup delle tue app.




Scopri di più su come https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html["Configurare Astra Control Center"^].

È possibile aggiungere applicazioni al cluster. In alternativa, se nel cluster gestito sono già presenti alcune applicazioni, è possibile utilizzare Astra Control Center per gestirle. Quindi, utilizza Astra Control Center per creare snapshot, backup, cloni e relazioni di replica.



== Per ulteriori informazioni

* https://docs.netapp.com/us-en/astra/index.html["Documentazione del servizio Astra Control"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Documentazione di Astra Control Center"^]
* https://docs.netapp.com/us-en/trident/index.html["Documentazione di Astra Trident"^]
* https://docs.netapp.com/us-en/astra-automation["Documentazione sull'API Astra Control"^]
* https://docs.netapp.com/us-en/cloudinsights/["Documentazione Cloud Insights"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentazione ONTAP"^]

