---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: 'Aggiungi e rimuovi le credenziali del cloud provider dal tuo account in qualsiasi momento. Astra utilizza queste credenziali per il provisioning delle risorse per conto dell"utente.' 
---
= Aggiungere e rimuovere le credenziali
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Aggiungi e rimuovi le credenziali per i provider di cloud privato locali, come ONTAP S3, i cluster Kubernetes gestiti con OpenShift o i cluster Kubernetes non gestiti dal tuo account in qualsiasi momento. Astra Control Center utilizza queste credenziali per scoprire i cluster Kubernetes e le applicazioni sui cluster e per eseguire il provisioning delle risorse per conto dell'utente.

Tutti gli utenti di Astra Control Center condividono gli stessi set di credenziali.



== Aggiungere credenziali

È possibile aggiungere credenziali ad Astra Control Center quando si gestiscono i cluster. Per aggiungere credenziali aggiungendo un nuovo cluster, fare riferimento a. link:../get-started/setup_overview.html#add-cluster["Aggiungere un cluster Kubernetes"].


NOTE: Se si crea il proprio file kubeconfig, si dovrebbe definire solo *un* elemento di contesto al suo interno. Fare riferimento a. https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Documentazione Kubernetes"^] per informazioni sulla creazione di file kubeconfig.



== Rimuovere le credenziali

Rimuovere le credenziali da un account in qualsiasi momento. Rimuovere le credenziali solo dopo link:unmanage.html["annullamento della gestione di tutti i cluster associati"].


NOTE: Il primo set di credenziali aggiunto ad Astra Control Center è sempre in uso perché Astra Control Center utilizza le credenziali per l'autenticazione nel bucket di backup. Si consiglia di non rimuovere queste credenziali.

.Fasi
. Selezionare *account*.
. Selezionare la scheda *credenziali*.
. Selezionare il menu Opzioni nella colonna *Stato* per le credenziali che si desidera rimuovere.
. Selezionare *Rimuovi*.
. Digitare la parola "remove" per confermare l'eliminazione, quindi selezionare *Sì, Rimuovi credenziale*.


.Risultato
Astra Control Center rimuove le credenziali dall'account.
