---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Descrive come rimuovere Astra Control Center e Astra Control Center Operator. 
---
= Disinstallare Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Potrebbe essere necessario rimuovere i componenti di Astra Control Center se si esegue l'aggiornamento da una versione di prova a una versione completa del prodotto. Per rimuovere Astra Control Center e Astra Control Center Operator, eseguire i comandi descritti in questa procedura in sequenza.

In caso di problemi con la disinstallazione, vedere <<Risoluzione dei problemi di disinstallazione>>.

.Prima di iniziare
. link:../use/unmanage.html#unmanage-an-app["Annulla gestione di tutte le applicazioni"^] sui cluster.
. link:../use/unmanage.html#unmanage-a-cluster["Annulla gestione di tutti i cluster"^].


.Fasi
. Eliminare Astra Control Center. Il seguente comando di esempio si basa su un'installazione predefinita. Modificare il comando se sono state create configurazioni personalizzate.
+
[listing]
----
kubectl delete -f astra_control_center.yaml -n netapp-acc
----
+
Risultato:

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Utilizzare il seguente comando per eliminare `netapp-acc` namespace (o personalizzato):
+
[listing]
----
kubectl delete ns [netapp-acc or custom namespace]
----
+
Risultato di esempio:

+
[listing]
----
namespace "netapp-acc" deleted
----
. Utilizzare il seguente comando per eliminare i componenti del sistema dell'operatore di Astra Control Center:
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Risultato:

+
[listing]
----
namespace/netapp-acc-operator deleted
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io deleted
role.rbac.authorization.k8s.io/acc-operator-leader-election-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role deleted
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding deleted
configmap/acc-operator-manager-config deleted
service/acc-operator-controller-manager-metrics-service deleted
deployment.apps/acc-operator-controller-manager deleted
----




== Risoluzione dei problemi di disinstallazione

Utilizzare le seguenti soluzioni alternative per risolvere eventuali problemi riscontrati durante la disinstallazione di Astra Control Center.



=== La disinstallazione di Astra Control Center non riesce a pulire il pod operatore di monitoraggio sul cluster gestito

Se i cluster non sono stati disgestiti prima della disinstallazione di Astra Control Center, è possibile eliminare manualmente i pod nello spazio dei nomi di monitoraggio netapp e nello spazio dei nomi con i seguenti comandi:

.Fasi
. Eliminare `acc-monitoring` agente:
+
[listing]
----
kubectl delete agents acc-monitoring -n netapp-monitoring
----
+
Risultato:

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. Eliminare lo spazio dei nomi:
+
[listing]
----
kubectl delete ns netapp-monitoring
----
+
Risultato:

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. Conferma la rimozione delle risorse:
+
[listing]
----
kubectl get pods -n netapp-monitoring
----
+
Risultato:

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. Conferma rimozione dell'agente di monitoraggio:
+
[listing]
----
kubectl get crd|grep agent
----
+
Risultato del campione:

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. Eliminare le informazioni CRD (Custom Resource Definition):
+
[listing]
----
kubectl delete crds agents.monitoring.netapp.com
----
+
Risultato:

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




=== La disinstallazione di Astra Control Center non consente di eliminare i CRD Traefik

È possibile eliminare manualmente i CRD Traefik. Le CRDS sono risorse globali e l'eliminazione di queste risorse potrebbe avere un impatto sulle altre applicazioni del cluster.

.Fasi
. Elencare i CRD Traefik installati sul cluster:
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
Risposta

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
middlewaretcps.traefik.containo.us            2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. Eliminare i CRD:
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us middlewaretcps.traefik.containo.us
----




== Trova ulteriori informazioni

* link:../release-notes/known-issues.html["Problemi noti per la disinstallazione"]

