---
sidebar: sidebar 
permalink: get-started/faq.html 
keywords: astra faq, astra frequently asked questions, what is astra, astra control, kubernetes, persistent volumes 
summary: Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda. 
---
= Domande frequenti per Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda.



== Panoramica

Le sezioni seguenti forniscono risposte ad alcune domande aggiuntive che potrebbero essere presentate durante l'utilizzo di Astra Control Center. Per ulteriori chiarimenti, contatta il sito astra.feedback@netapp.com



== Accesso al centro di controllo Astra

*Cos'è l'URL di Astra Control?*

Astra Control Center utilizza l'autenticazione locale e un URL specifico per ciascun ambiente.

Per l'URL, in un browser, immettere il nome di dominio completo (FQDN) impostato nel campo spec.astraAddress nel file di risorsa personalizzata (CR) astra_control_center.yaml quando si installa Astra Control Center. L'email è il valore impostato nel campo spec.email in astra_control_center.yaml CR.



== Licensing

*Utilizzo una licenza di valutazione. Come si passa alla licenza completa?*

È possibile passare facilmente a una licenza completa ottenendo il file di licenza NetApp (NLF) da NetApp.

*Fasi*

. Dalla barra di navigazione a sinistra, selezionare *account* > *licenza*.
. Nella panoramica della licenza, a destra delle informazioni sulla licenza, selezionare il menu Opzioni.
. Selezionare *Sostituisci*.
. Individuare il file di licenza scaricato e selezionare *Aggiungi*.


*Utilizzo una licenza di valutazione. Posso comunque gestire le applicazioni?*

Sì, è possibile testare la funzionalità di gestione delle applicazioni con una licenza di valutazione (inclusa la licenza di valutazione integrata installata per impostazione predefinita). Non vi è alcuna differenza in termini di funzionalità tra una licenza di valutazione e una licenza completa; la licenza di valutazione ha semplicemente una durata inferiore. Fare riferimento a. link:../concepts/licensing.html["Licensing"^] per ulteriori informazioni.



== Registrazione dei cluster Kubernetes

*Devo aggiungere nodi di lavoro al cluster Kubernetes dopo l'aggiunta ad Astra Control. Cosa devo fare?*

È possibile aggiungere nuovi nodi di lavoro ai pool esistenti. Questi verranno rilevati automaticamente da Astra Control. Se i nuovi nodi non sono visibili in Astra Control, controllare se i nuovi nodi di lavoro eseguono il tipo di immagine supportato. È inoltre possibile verificare lo stato dei nuovi nodi di lavoro utilizzando `kubectl get nodes` comando.

*Come si annulla la gestione corretta di un cluster?*

. link:../use/unmanage.html["Annulla la gestione delle applicazioni da Astra Control"].
. link:../use/unmanage.html#stop-managing-compute["Annullare la gestione del cluster da Astra Control"].


*Cosa succede alle mie applicazioni e ai miei dati dopo aver rimosso il cluster Kubernetes da Astra Control?*

La rimozione di un cluster da Astra Control non apporta alcuna modifica alla configurazione del cluster (applicazioni e storage persistente). Eventuali snapshot di Astra Control o backup delle applicazioni su quel cluster non saranno disponibili per il ripristino. I backup persistenti dello storage creati da Astra Control rimangono all'interno di Astra Control, ma non sono disponibili per il ripristino.


WARNING: Rimuovere sempre un cluster da Astra Control prima di eliminarlo con altri metodi. L'eliminazione di un cluster utilizzando un altro tool mentre viene ancora gestito da Astra Control può causare problemi all'account Astra Control.

*NetApp Astra Trident viene disinstallato automaticamente da un cluster quando viene disgestito?* quando si disgestisce un cluster da Astra Control Center, Astra Trident non viene disinstallato automaticamente dal cluster. Per disinstallare Astra Trident, è necessario https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Seguire questa procedura nella documentazione di Astra Trident"^].



== Gestione delle applicazioni

*Astra Control può implementare un'applicazione?*

Astra Control non implementa le applicazioni. Le applicazioni devono essere implementate all'esterno di Astra Control.

*Cosa succede alle applicazioni dopo che non li gestisco da Astra Control?*

Eventuali backup o snapshot esistenti verranno eliminati. Le applicazioni e i dati rimangono disponibili. Le operazioni di gestione dei dati non saranno disponibili per le applicazioni non gestite o per eventuali backup o snapshot ad esse appartenenti.

* Astra Control può gestire un'applicazione su storage non NetApp?*

No Mentre Astra Control è in grado di rilevare applicazioni che utilizzano storage non NetApp, non può gestire un'applicazione che utilizza storage non NetApp.

*Dovrei gestire Astra Control da solo?*

No, non si dovrebbe gestire Astra Control da solo perché si tratta di un'applicazione di sistema.

*I pod malsani influiscono sulla gestione delle applicazioni?*

No, la salute dei pod non influisce sulla gestione delle app.



== Operazioni di gestione dei dati

*La mia applicazione utilizza diversi PVS. Astra Control eseguirà snapshot e backup di questi PVS?*

Sì. Un'operazione snapshot su un'applicazione di Astra Control include snapshot di tutti i PVS associati ai PVC dell'applicazione.

*È possibile gestire le snapshot acquisite da Astra Control direttamente attraverso un'interfaccia o un'archiviazione a oggetti diversa?*

No Le snapshot e i backup eseguiti da Astra Control possono essere gestiti solo con Astra Control.
