---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters, tanzu, tkg, tkgi, grid, kubernetes, k8s 
summary: Inizia a utilizzare Astra Control Center verificando il supporto per cluster, applicazioni e browser Web Kubernetes. 
---
= Requisiti di Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Inizia verificando la preparazione del tuo ambiente operativo, dei cluster di applicazioni, delle applicazioni, delle licenze e del browser Web. Assicurati che il tuo ambiente soddisfi questi requisiti per implementare e utilizzare Astra Control Center.



== Ambienti Kubernetes cluster host supportati

Astra Control Center è stato validato con i seguenti ambienti host Kubernetes:


NOTE: Assicurarsi che l'ambiente Kubernetes scelto per ospitare Astra Control Center soddisfi i requisiti di base delle risorse descritti nella documentazione ufficiale dell'ambiente.

|===
| Distribuzione di Kubernetes sul cluster host | Versioni supportate 


| Azure Kubernetes Service su Azure Stack HCI | Stack Azure HCI 21H2 e 22H2 con AKS 1.24.11 fino a 1.26.6 


| Google anthos | Da 1,15 a 1,16 (vedere <<Requisiti di ingresso di Google anthos>>) 


| Kubernetes (upstream) | da 1,27 a 1,29 


| Rancher Kubernetes Engine (RKE) | RKE 1: Versioni 1.24.17, 1.25.13, 1.26.8 con Rancher Manager 2.7.9
RKE 2: Versioni 1.23.16 e 1.24.13 con Rancher Manager 2.6.13
RKE 2: Versioni 1.24.17, 1.25.14, 1.26.9 con Rancher Manager 2.7.9 


| Red Hat OpenShift Container Platform | da 4,12 a 4,14 
|===


== Requisiti delle risorse del cluster host

Astra Control Center richiede le seguenti risorse oltre ai requisiti delle risorse dell'ambiente:


NOTE: Questi requisiti presuppongono che Astra Control Center sia l'unica applicazione in esecuzione nell'ambiente operativo. Se nell'ambiente sono in esecuzione applicazioni aggiuntive, modificare di conseguenza questi requisiti minimi.

* *CPU Extensions*: Le CPU di tutti i nodi dell'ambiente di hosting devono avere le estensioni AVX abilitate.
* *Nodi di lavoro*: Almeno 3 nodi di lavoro in totale, con 4 core CPU e 12 GB di RAM ciascuno
* *Requisiti del cluster VMware Tanzu Kubernetes Grid*: Quando si ospita Astra Control Center su un cluster VMware Tanzu Kubernetes Grid (TKG) o Tanzu Kubernetes Grid Integrated Edition (TKGi), tenere presente le seguenti considerazioni.
+
** Il token del file di configurazione predefinito di VMware TKG e TKGi scade dieci ore dopo l'implementazione. Se si utilizzano prodotti del portfolio Tanzu, è necessario generare un file di configurazione del cluster Tanzu Kubernetes con un token non in scadenza per evitare problemi di connessione tra Astra Control Center e cluster di applicazioni gestiti. Per istruzioni, visitare il sito https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/nsx-application-platform/GUID-52A52C0B-9575-43B6-ADE2-E8640E22C29F.html["Documentazione del prodotto VMware NSX-T Data Center."^]
** Utilizzare `kubectl get nsxlbmonitors -A` per verificare se è già stato configurato un monitor dei servizi per accettare il traffico in entrata. Se ne esiste uno, non installare MetalLB, perché il monitor di servizio esistente sovrascriverà qualsiasi nuova configurazione del bilanciamento del carico.
** Disattivare l'applicazione della classe di storage predefinita TKG o TKGi su qualsiasi cluster di applicazioni che deve essere gestito da Astra Control. Per eseguire questa operazione, modificare il `TanzuKubernetesCluster` risorsa sul cluster dello spazio dei nomi.
** Quando implementi Astra Control Center in un ambiente TKG o TKGi, tieni presente i requisiti specifici di Astra Control Provisioner:
+
*** Il cluster deve supportare workload con privilegi.
*** Il `--kubelet-dir` flag deve essere impostato sulla posizione della directory di kubelet. Per impostazione predefinita, questo è `/var/vcap/data/kubelet`.
*** Specificare la posizione del kubelet utilizzando `--kubelet-dir` È noto per lavorare con Trident Operator, Helm e. `tridentctl` implementazioni.








== Requisiti mesh di servizio

Si consiglia vivamente di installare una versione vanilla supportata della mesh del servizio Istio sul cluster host Astra Control Center. Fare riferimento a. https://istio.io/latest/docs/releases/supported-releases/["versioni supportate"^] Per le versioni supportate di Istio. Le versioni con marchio di Istio Service Mesh, come OpenShift Service Mesh, non sono validate con Astra Control Center.

Per integrare Astra Control Center con la mesh di servizio Istio installata sul cluster host, è necessario eseguire l'integrazione come parte di Astra Control Center link:../get-started/install_acc.html["installazione"] e non indipendente da questo processo.


NOTE: L'installazione e l'utilizzo di Astra Control Center senza la configurazione di una mesh di servizio nel cluster host ha potenzialmente serie implicazioni per la sicurezza.



== Astra Trident

Se intendi utilizzare Astra Trident al posto di Astra Control Provivisioner con questa release, sono supportate Astra Trident 23,04 e versioni successive. Astra Control Center richiede <<Astra Control provisioner>> nelle versioni future.



== Astra Control provisioner

Per utilizzare le funzionalità di storage avanzate di Astra Control Provivisioner, devi installare Astra Trident 23,10 o versioni successive e abilitare link:../get-started/enable-acp.html["Funzionalità Astra Control Provisioner"]. Per utilizzare la funzionalità più recente di Astra Control Provisioner, avrai bisogno delle versioni più recenti di Astra Trident e Astra Control Center.

* *Versione minima di Astra Control Provisioner da utilizzare con Astra Control Center*: Astra Control Provisioner 23,10 o versione successiva installato e configurato.




=== Configurazione di ONTAP con Astra Trident

* *Storage class*: Configurare almeno una classe di archiviazione nel cluster. Se viene configurata una classe di storage predefinita, assicurarsi che sia l'unica classe di storage con la designazione predefinita.
* *Driver di storage e nodi di lavoro*: Assicurarsi di configurare i nodi di lavoro nel cluster con i driver di storage appropriati in modo che i pod possano interagire con lo storage backend. Centro di controllo Astra supporta i seguenti driver ONTAP forniti da Astra Trident:
+
** `ontap-nas`
** `ontap-san`
** `ontap-san-economy` (la replica dell'applicazione non è disponibile con questo tipo di classe di archiviazione)
** `ontap-nas-economy` (le snapshot e le policy di replica delle applicazioni non sono disponibili con questo tipo di classe di storage)






== Back-end dello storage

Assicurarsi di disporre di un backend supportato con capacità sufficiente.

* *Capacità di back-end dello storage richiesta*: Almeno 500 GB disponibili
* *Backend supportati*: Astra Control Center supporta i seguenti backend di storage:
+
** NetApp ONTAP 9.9.1 o sistemi AFF, FAS e ASA successivi
** NetApp ONTAP Select 9.9.1 o versione successiva
** NetApp Cloud Volumes ONTAP 9.9.1 o versione successiva
** (Per l'anteprima tecnica Astra Control Center) NetApp ONTAP 9.10.1 o versioni successive per le operazioni di protezione dei dati fornite come anteprima tecnica
** Longhorn 1.5.0 o successivo
+
*** Richiede la creazione manuale di un oggetto VolumeSnapshotClass. Fare riferimento a. https://longhorn.io/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/#create-a-csi-volumesnapshot-associated-with-longhorn-snapshot["Documentazione di Longhorn"^] per istruzioni.


** NetApp MetroCluster
+
*** I cluster Kubernetes gestiti devono essere in una configurazione stretch.


** Backend di storage disponibili con cloud provider supportati






=== Licenze ONTAP

Per utilizzare il centro di controllo Astra, verificare di disporre delle seguenti licenze ONTAP, a seconda delle operazioni da eseguire:

* FlexClone
* SnapMirror: Opzionale. Necessario solo per la replica su sistemi remoti utilizzando la tecnologia SnapMirror. Fare riferimento a. https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Informazioni sulla licenza SnapMirror"^].
* Licenza S3: Opzionale. Necessario solo per i bucket ONTAP S3


Per verificare se il sistema ONTAP dispone delle licenze richieste, fare riferimento a. https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Gestire le licenze ONTAP"^].



=== NetApp MetroCluster

Quando utilizzi NetApp MetroCluster come back-end dello storage, devi quanto segue:

* Specifica una LIF di gestione SVM come opzione di backend nel driver Astra Trident che utilizzi
* Assicurarsi di disporre della licenza ONTAP appropriata


Per configurare la LIF MetroCluster, fai riferimento a queste opzioni ed esempi per ogni driver:

* https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["SAN"^]
* https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html["NAS"^]




== Licenza Astra Control Center

Astra Control Center richiede una licenza Astra Control Center. Quando si installa Astra Control Center, viene già attivata una licenza di valutazione integrata di 90 giorni per 4,800 unità CPU. Se hai bisogno di una maggiore capacità o di termini di valutazione diversi, o se desideri passare a una licenza completa, puoi ottenere una licenza di valutazione o una licenza completa diversa da NetApp. Hai bisogno di una licenza per proteggere le tue applicazioni e i tuoi dati.

Puoi provare Astra Control Center registrandoti per una prova gratuita. Puoi iscriverti registrandoti link:https://bluexp.netapp.com/astra-register["qui"^].

Per impostare la licenza, fare riferimento a. link:add-license.html["utilizzare una licenza di valutazione di 90 giorni"].

Per ulteriori informazioni sul funzionamento delle licenze, fare riferimento a. link:../concepts/licensing.html["Licensing"].



== Requisiti di rete

Configura il tuo ambiente operativo per garantire che Astra Control Center possa comunicare correttamente. Sono necessarie le seguenti configurazioni di rete:

* *Indirizzo FQDN*: È necessario disporre di un indirizzo FQDN per Astra Control Center.
* *Accesso a Internet*: È necessario determinare se si dispone di accesso esterno a Internet. In caso contrario, alcune funzionalità potrebbero essere limitate, ad esempio l'invio di pacchetti di supporto al https://mysupport.netapp.com/site/["Sito di supporto NetApp"^].
* *Port Access*: L'ambiente operativo che ospita Astra Control Center comunica utilizzando le seguenti porte TCP. Assicurarsi che queste porte siano consentite attraverso qualsiasi firewall e configurare i firewall in modo da consentire qualsiasi traffico HTTPS in uscita dalla rete Astra. Alcune porte richiedono la connettività tra l'ambiente che ospita Astra Control Center e ciascun cluster gestito (annotato dove applicabile).



NOTE: Puoi implementare Astra Control Center in un cluster Kubernetes dual-stack, mentre Astra Control Center può gestire le applicazioni e i back-end di storage configurati per il funzionamento dual-stack. Per ulteriori informazioni sui requisiti del cluster dual-stack, vedere https://kubernetes.io/docs/concepts/services-networking/dual-stack/["Documentazione Kubernetes"^].

|===
| Origine | Destinazione | Porta | Protocollo | Scopo 


| PC client | Centro di controllo Astra | 443 | HTTPS | Accesso UI/API - assicurarsi che questa porta sia aperta in entrambe le direzioni tra Astra Control Center e il sistema utilizzato per accedere ad Astra Control Center 


| Metriche consumer | Nodo di lavoro Astra Control Center | 9090 | HTTPS | Comunicazione dei dati delle metriche - garantire che ciascun cluster gestito possa accedere a questa porta sul cluster che ospita Astra Control Center (è richiesta una comunicazione bidirezionale) 


| Centro di controllo Astra | Provider di bucket di storage Amazon S3 | 443 | HTTPS | Comunicazione con lo storage Amazon S3 


| Centro di controllo Astra | NetApp AutoSupport (https://support.netapp.com[]) | 443 | HTTPS | Comunicazioni NetApp AutoSupport 


| Centro di controllo Astra | Cluster Kubernetes gestito | 443/6443
*NOTA*: La porta utilizzata dal cluster gestito può variare a seconda del cluster. Fare riferimento alla documentazione fornita dal fornitore del software per cluster. | HTTPS | Comunicazione con il cluster gestito - assicurarsi che questa porta sia aperta in entrambi i modi tra il cluster che ospita Astra Control Center e ciascun cluster gestito 
|===


== Ingresso per cluster Kubernetes on-premise

È possibile scegliere il tipo di ingresso di rete utilizzato da Astra Control Center. Per impostazione predefinita, Astra Control Center implementa il gateway Astra Control Center (servizio/traefik) come risorsa a livello di cluster. Astra Control Center supporta anche l'utilizzo di un servizio di bilanciamento del carico, se consentito nel tuo ambiente. Se si preferisce utilizzare un servizio di bilanciamento del carico e non ne si dispone già di uno configurato, è possibile utilizzare il bilanciamento del carico MetalLB per assegnare automaticamente un indirizzo IP esterno al servizio. Nella configurazione del server DNS interno, puntare il nome DNS scelto per Astra Control Center sull'indirizzo IP con bilanciamento del carico.


NOTE: Il bilanciamento del carico deve utilizzare un indirizzo IP situato nella stessa subnet degli indirizzi IP del nodo di lavoro di Astra Control Center.

Per ulteriori informazioni, fare riferimento a. link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["Impostare l'ingresso per il bilanciamento del carico"].



=== Requisiti di ingresso di Google anthos

Quando si ospita Astra Control Center su un cluster Google anthos, Google anthos include il bilanciamento del carico MetalLB e il servizio di ingresso Istio per impostazione predefinita, consentendo di utilizzare semplicemente le funzionalità di ingresso generiche di Astra Control Center durante l'installazione. Fare riferimento a. link:install_acc.html#configure-astra-control-center["Documentazione di installazione di Astra Control Center"] per ulteriori informazioni.



== Browser Web supportati

Astra Control Center supporta versioni recenti di Firefox, Safari e Chrome con una risoluzione minima di 1280 x 720.



== Requisiti aggiuntivi per i cluster di applicazioni

Se si prevede di utilizzare queste funzionalità di Astra Control Center, tenere presenti questi requisiti:

* *Requisiti del cluster applicativo*: link:../get-started/prep-for-cluster-management.html["Requisiti di gestione del cluster"]
+
** *Requisiti delle applicazioni gestite*: link:../use/manage-apps.html#application-management-requirements["Requisiti di gestione delle applicazioni"]
** *Requisiti aggiuntivi per la replica delle applicazioni*: link:../use/replicate_snapmirror.html#replication-prerequisites["Prerequisiti per la replica"]






== Cosa succederà

Visualizzare il link:quick-start.html["avvio rapido"] panoramica.
